# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GDN - XBook
author: The Macrometa Team
copyright: "2022"
logo: ./images/logo-macrometa.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""
  colab_url                 : https://colab.research.google.com

# Information about where the book exists on the web
repository:
  url: https://github.com/Macrometacorp/notebooks  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
